### ISSUE TITLE
implementation source

### ISSUE THREAD

**Issue by mj-sam** [semesterprojectBCI/bci-classification#1]
hello
you did a good job implementing this code , 
but would it would be great help if you  mention the source of your method
thank you

**Comment by tinorellstab** [comment]
Hi,
Please have a look at our paper we wrote for Eusipco 2018:
[Fast_and_Accurate_Multiclass_Inference_for_MI-BCIs.pdf](https://github.com/MultiScale-BCI/IV-2a/files/2111134/Fast_and_Accurate_Multiclass_Inference_for_MI-BCIs.pdf)
Best regards,
Tino
