### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by tp4069** [semesterprojectBCI/bci-classification#3]
Hi sir,

I got this error while running on Colab

KeyError                                  Traceback (most recent call last)
[<ipython-input-10-c64f195aa013>](https://localhost:8080/#) in <module>()
    192 
    193 if __name__ == '__main__':
--> 194         main()

2 frames
[/content/get_data.py](https://localhost:8080/#) in get_data(subject, training, PATH)
     55                         data_return = np.zeros((NO_tests,NO_channels,Window_Length))
     56 
---> 57         a_data = a['data']
     58         total_trials = 0
     59         for ii in range(0,a_data.size):

KeyError: 'data'

Kindly give any suggestions to solve the error.

Thankyou

**Comment by MHersche** [comment]
Hi, did you download the dataset from the link which is given in the README?

**Comment by tp4069** [comment]
Hi sir,

Yes, I download the dataset file

A01T.mat  ............. A09T.mat
A01E.mat  ............ A09E.mat
A01T.gdf ............... A09T.gdf
A01E.gdf ............... A09E.gdf

All the above files are copied under the dataset folder and this link has
been given in the "main_csp.py".

self.data_path =
'C:/Users/admin/Downloads/IV-2a-master/IV-2a-master/dataset/'

But the error is in get_data.py

a_data = a['data']

Expecting your kind reply sir

Thankyou

**Comment by tinorellstab** [comment]
Works fine in my colab setup. Your data path does not look right. I think you need to upload the dataset to colab.
<img width="1792" alt="Screenshot 2022-02-19 at 11 50 33" src="https://user-images.githubusercontent.com/11900652/154797815-b37a374e-d15e-49e5-8786-67d03eea9c3e.png">

**Comment by tp4069** [comment]
hi
I got the same error. I attached my screen shots for your kind reference.

![2](https://user-images.githubusercontent.com/88485915/154798572-073a1e07-8f38-4e19-a73d-c9c8a5ca5110.png)
![1](https://user-images.githubusercontent.com/88485915/154798574-4793d11f-e763-4c57-ac4c-cdd37f2ce356.png)

**Comment by tinorellstab** [comment]
Maybe there is a problem with your dataset. Does this help?
`!rm -rf dataset/*`
`!wget http://bnci-horizon-2020.eu/database/data-sets/001-2014/A01T.mat `
`!wget http://bnci-horizon-2020.eu/database/data-sets/001-2014/A01E.mat `
`!mv A*.mat dataset/`

**Comment by tp4069** [comment]
Hi sir,
Thank you for your reply. The program is working now.
Some changes have been done to the program by you, I hope so.
Also, I am trying to plot the confusion matrix, etc.,
Thankyou sir
